In [11]:
import pandas as pd
import json
from methods import grabber 
from methods.pandas_process import posts_transfrom_json_to_pandas
from methods.pandas_process import likes_to_recsys_matrix
import time

In [2]:
f = grabber.get_items_of_page("170528132", count=8)

Start parsing

100%|██████████| 8/8 [00:04<00:00,  1.97it/s]

In [8]:
# how to filter active users >
active_users = recsys_matrix.loc[:, (~recsys_matrix.isna()).sum() > 3].columns

In [ ]:
recsys_matrix.loc[:, (~recsys_matrix.isna()).sum() > 3]

In [54]:
for col in ["career", "military"]:
    uinfodf.loc[~uinfodf[col].isna(), col] = uinfodf.loc[~uinfodf[col].isna(), col].apply(lambda x: x[-1] if (not isinstance(x, float) and len(x) > 0 ) else pd.NA)
    vcarer = pd.json_normalize(uinfodf[col])
    uinfodf.loc[:, [i+f"_{col}" for i in vcarer.columns]] = vcarer
    uinfodf = uinfodf.drop(col, axis=1)

In [53]:
uinfodf = pd.json_normalize(users_info)
uinfodf

          id       bdate  ... counters.posts occupation.graduate_year
0  496606416    2.5.2000  ...            NaN                      NaN
1  530601295   10.5.2000  ...            NaN                      NaN
2  537900720        29.3  ...            NaN                      NaN
3  583171089  26.12.1995  ...           12.0                      NaN
4  643059940   26.7.2000  ...            NaN                      NaN
5  815352499  25.11.1997  ...           19.0                   2021.0

[6 rows x 56 columns]

In [15]:
users_info = []
for j in active_users:
    users_info.append(grabber.user_request(j))
    time.sleep(0.4)
users_info

[{'id': 496606416,
  'bdate': '2.5.2000',
  'city': {'id': 60, 'title': 'Kazan'},
  'country': {'id': 1, 'title': 'Russia'},
  'interests': '',
  'books': '',
  'games': '',
  'movies': '',
  'activities': '',
  'music': '',
  'followers_count': 89,
  'career': [],
  'military': [],
  'university': 0,
  'university_name': '',
  'faculty': 0,
  'faculty_name': '',
  'graduation': 0,
  'home_town': 'Казань',
  'relation': 0,
  'personal': {'alcohol': 0,
   'inspired_by': '',
   'langs': ['Русский'],
   'langs_full': [{'id': 0, 'native_name': 'Русский'}],
   'life_main': 0,
   'people_main': 0,
   'smoking': 0},
  'universities': [],
  'schools': [],
  'counters': {'albums': 2,
   'audios': 0,
   'followers': 60,
   'gifts': 53,
   'groups': 132,
   'pages': 99,
   'photos': 15,
   'subscriptions': 1,
   'videos': 64,
   'video_playlists': 0,
   'clips_followers': 88},
  'sex': 2,
  'verified': 0,
  'friend_status': 0,
  'first_name': 'Dinar',
  'last_name': 'Paleev',
  'can_access_closed': True,
  'is_closed': False},
 {'id': 530601295,
  'bdate': '10.5.2000',
  'city': {'id': 110, 'title': 'Perm'},
  'country': {'id': 1, 'title': 'Russia'},
  'interests': '',
  'books': '',
  'games': '',
  'movies': '',
  'activities': '',
  'music': '',
  'followers_count': 93,
  'occupation': {'id': 147059159, 'name': 'ЧБG', 'type': 'work'},
  'career': [{'country_id': 1, 'from': 2018, 'group_id': 147059159}],
  'military': [],
  'university': 0,
  'university_name': '',
  'faculty': 0,
  'faculty_name': '',
  'graduation': 0,
  'home_town': '',
  'relation': 0,
  'personal': {'alcohol': 0,
   'inspired_by': 'Животные',
   'life_main': 0,
   'people_main': 6,
   'smoking': 4},
  'universities': [],
  'schools': [],
  'counters': {'albums': 1,
   'audios': 0,
   'followers': 66,
   'gifts': 102,
   'groups': 37,
   'pages': 23,
   'photos': 12,
   'subscriptions': 3,
   'videos': 51,
   'video_playlists': 0,
   'clips_followers': 93},
  'sex': 2,
  'verified': 0,
  'friend_status': 0,
  'first_name': 'Matvey',
  'last_name': 'Kot',
  'can_access_closed': True,
  'is_closed': False},
 {'id': 537900720,
  'bdate': '29.3',
  'city': {'id': 1803188, 'title': 'Kohtla-Järve'},
  'country': {'id': 14, 'title': 'Estonia'},
  'interests': '',
  'books': '',
  'games': '',
  'movies': '',
  'activities': '',
  'music': '',
  'followers_count': 253,
  'career': [],
  'military': [],
  'university': 0,
  'university_name': '',
  'faculty': 0,
  'faculty_name': '',
  'graduation': 0,
  'home_town': 'Kohtla-Järve (Кохтла-Ярве)',
  'relation': 0,
  'personal': {'alcohol': 4,
   'inspired_by': '',
   'langs': ['Русский', 'English'],
   'langs_full': [{'id': 0, 'native_name': 'Русский'},
    {'id': 3, 'native_name': 'English'}],
   'life_main': 0,
   'people_main': 0,
   'smoking': 4},
  'universities': [],
  'schools': [],
  'counters': {'albums': 0,
   'audios': 0,
   'followers': 237,
   'pages': 34,
   'photos': 1,
   'subscriptions': 21,
   'videos': 89,
   'video_playlists': 0,
   'clips_followers': 253},
  'sex': 2,
  'verified': 0,
  'friend_status': 0,
  'first_name': 'Alexander',
  'last_name': 'Morozov',
  'can_access_closed': True,
  'is_closed': False},
 {'id': 583171089,
  'bdate': '26.12.1995',
  'city': {'id': 1, 'title': 'Moscow'},
  'country': {'id': 1, 'title': 'Russia'},
  'occupation': {'id': 213,
   'name': 'МГЮА (Университет им. О. Е. Кутафина)',
   'type': 'university',
   'country_id': 1,
   'city_id': 1},
  'counters': {'albums': 0,
   'audios': 0,
   'pages': 29,
   'subscriptions': 0,
   'videos': 0,
   'video_playlists': 0,
   'posts': 12},
  'sex': 2,
  'verified': 0,
  'friend_status': 0,
  'first_name': 'Sergey',
  'last_name': 'Isaev',
  'can_access_closed': False,
  'is_closed': True},
 {'id': 643059940,
  'bdate': '26.7.2000',
  'interests': '',
  'books': '',
  'games': '',
  'movies': '',
  'activities': '',
  'music': '',
  'followers_count': 212,
  'career': [],
  'military': [],
  'university': 0,
  'university_name': '',
  'faculty': 0,
  'faculty_name': '',
  'graduation': 0,
  'home_town': '',
  'relation': 0,
  'universities': [],
  'schools': [],
  'counters': {'albums': 3,
   'audios': 171,
   'followers': 82,
   'gifts': 42,
   'groups': 210,
   'pages': 156,
   'photos': 1,
   'subscriptions': 13,
   'videos': 416,
   'video_playlists': 0,
   'clips_followers': 212},
  'sex': 2,
  'verified': 0,
  'friend_status': 0,
  'first_name': 'Freestyle',
  'last_name': 'Federalov',
  'can_access_closed': True,
  'is_closed': False},
 {'id': 815352499,
  'bdate': '25.11.1997',
  'occupation': {'id': 31425,
   'name': 'Hochschule für Wirtschaft und Recht Berlin (ehem. FHW, FHVR)',
   'type': 'university',
   'graduate_year': 2021,
   'country_id': 65,
   'city_id': 458},
  'counters': {'albums': 0,
   'audios': 0,
   'pages': 36,
   'subscriptions': 2,
   'videos': 0,
   'video_playlists': 0,
   'posts': 19},
  'sex': 2,
  'verified': 0,
  'friend_status': 0,
  'first_name': 'Dmitry',
  'last_name': 'Skamlingov',
  'can_access_closed': False,
  'is_closed': True}]

In [4]:
users = recsys_matrix[(~recsys_matrix.isna()).sum() > 3].columns

NameError: name 'recsys_matrix' is not defined

In [5]:
recsys_matrix = likes_to_recsys_matrix(f)

In [3]:
df = posts_transfrom_json_to_pandas(f)

In [18]:
dfres = []
for i in f["likes"]:
    postid = i["post_id"]
    likes = i["likes"]
    for j in likes:
        dfres.append([postid, j])

df = pd.DataFrame(dfres)
sparse_matrix = df.pivot_table(index=0, columns=1, aggfunc="size")
sparse_matrix

1,1066051,1312963,1776177,3780549,4642016,5039337,5474207,5653767,6456019,8164867,...,791885188,792598878,794914520,804153012,811375288,815352499,815430976,827530009,831028729,831837014
0,,,,,,,,,,,,,,,,,,,,,
5467687,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
5467728,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN
5467764,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5467845,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
5467891,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0
5467943,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,...,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
5467999,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5468064,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df

,post_id,marked_as_ads,date,id,post_type,text,owner,photo_text,photo_date,donut.is_donut,...,video_duration,video_description,carousel_offset,neutral,negative,skip,positive,hashtags,tfidf,lda
0,-170528132_5468064,0,2023-11-13 09:50:00,5468064,post,Книжный продавец почти год гордо отстаивает св...,1,,2023-11-13 01:15:18,False,...,NaN,NaN,NaN,0.569863,0.314061,NaN,NaN,[],"{'000': 0.32608166589625326, '1500': 0.3260816...","[(0, 0.014350337), (1, 0.01430117), (2, 0.0143..."
1,-170528132_5467999,0,2023-11-13 08:50:00,5467999,post,Алкоголь после кофе улучшает сон вечером и обе...,1,,2023-11-13 01:14:59,False,...,NaN,NaN,NaN,0.430157,0.355785,NaN,NaN,[],"{'000': 0.13722195637203086, '1500': 0.1372219...","[(2, 0.98514223)]"
2,-170528132_5467943,0,2023-11-13 07:50:00,5467943,post,"В Таиланде задержали мужчину из России, которы...",1,,2023-11-13 01:14:46,False,...,NaN,NaN,NaN,0.355785,NaN,0.201823,NaN,[],"{'000': 0.23308958632979296, '1500': 0.2781239...","[(1, 0.96511066)]"
3,-170528132_5467891,0,2023-11-13 06:50:00,5467891,post,"Совет да любовь, так сказатб",1,,2023-11-13 01:14:14,False,...,NaN,NaN,NaN,0.538993,NaN,0.058356,NaN,[],"{'000': 0.5773502691896258, '1500': 0.57735026...","[(0, 0.033335328), (1, 0.033336926), (2, 0.033..."
4,-170528132_5467845,1,2023-11-13 05:50:00,5467845,post,"Возьму 2-3 человека, которые хотят зарабатыват...",1,,2023-11-12 12:20:16,False,...,NaN,NaN,NaN,0.812877,0.140346,NaN,NaN,[],"{'000': 0.05728555921243425, '1500': 0.0572855...","[(0, 0.9971873)]"
5,-170528132_5467764,0,2023-11-13 04:50:00,5467764,post,"В России могут начать штрафовать родителей, чь...",1,,2023-11-13 01:14:04,False,...,NaN,NaN,NaN,0.787941,NaN,0.177821,NaN,[],"{'000': 0.21355163150844386, '1500': 0.2135516...","[(1, 0.9679903)]"
6,-170528132_5467728,0,2023-11-13 04:00:02,5467728,post,"Британский бренд Vollebak выпустил одежду, кот...",1,NaN,NaT,False,...,47.0,47.0,NaN,0.718604,0.098089,NaN,NaN,[],"{'000': 0.16214701791116465, '1500': 0.1621470...","[(1, 0.98566574)]"
7,-170528132_5467687,0,2023-11-13 03:00:01,5467687,post,Найден идеальный колпачок для зубной пасты. \n...,1,,2023-11-13 01:33:33,False,...,9.0,9.0,0.0,0.651365,NaN,NaN,0.187143,[],"{'000': 0.30151134457776363, '1500': 0.3015113...","[(0, 0.015393868), (1, 0.015386225), (2, 0.015..."

In [6]:
df.columns

Index(['post_id', 'marked_as_ads', 'date', 'id', 'post_type', 'text', 'owner',
       'photo_text', 'photo_date', 'donut.is_donut', 'comments.count',
       'likes.count', 'reposts.count', 'views.count', 'video_comments',
       'video_date', 'video_duration', 'video_description', 'carousel_offset',
       'neutral', 'negative', 'skip', 'positive', 'hashtags'],
      dtype='object')

In [3]:
df = pd.json_normalize([{"post_id": i["post_id"], **i["post_info"]} for i in f["posts"]])
for i in ["date", "photo_date", "video_date"]:
    df.loc[:, i] = pd.to_datetime(df[i], unit='s', origin='unix') 
df

,post_id,marked_as_ads,date,id,post_type,text,owner,photo_text,photo_date,donut.is_donut,comments.count,likes.count,reposts.count,views.count,video_comments,video_date,video_duration,video_description,carousel_offset
0,-170528132_5467999,0,2023-11-13 08:50:00,5467999,post,Алкоголь после кофе улучшает сон вечером и обе...,1,,2023-11-13 01:14:59,False,8,28,44,3594,NaN,NaT,NaN,NaN,NaN
1,-170528132_5467943,0,2023-11-13 07:50:00,5467943,post,"В Таиланде задержали мужчину из России, которы...",1,,2023-11-13 01:14:46,False,19,219,81,36147,NaN,NaT,NaN,NaN,NaN
2,-170528132_5467891,0,2023-11-13 06:50:00,5467891,post,"Совет да любовь, так сказатб",1,,2023-11-13 01:14:14,False,18,268,177,40832,NaN,NaT,NaN,NaN,NaN
3,-170528132_5467845,1,2023-11-13 05:50:00,5467845,post,"Возьму 2-3 человека, которые хотят зарабатыват...",1,,2023-11-12 12:20:16,False,0,6,1,33625,NaN,NaT,NaN,NaN,NaN
4,-170528132_5467764,0,2023-11-13 04:50:00,5467764,post,"В России могут начать штрафовать родителей, чь...",1,,2023-11-13 01:14:04,False,44,210,150,49170,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-170528132_5456794,0,2023-11-08 10:00:02,5456794,post,В России бездомных собак начнут кормить красно...,1,,2023-11-08 02:27:43,False,112,361,504,71855,NaN,NaT,NaN,NaN,NaN
96,-170528132_5456148,0,2023-11-08 08:30:00,5456148,post,15-летний Адам Кадыров пришёл на награждение к...,1,,2023-11-08 02:26:59,False,521,272,314,101915,NaN,NaT,NaN,NaN,NaN
97,-170528132_5455818,0,2023-11-08 07:00:06,5455818,post,Библиотеки в России выдают книги «иноагентов» ...,1,,2023-11-08 02:26:00,False,107,164,141,76552,NaN,NaT,NaN,NaN,NaN
98,-170528132_5455647,0,2023-11-08 06:00:04,5455647,post,Глава Кабардино-Балкарии Казбек Коков вручил А...,1,,2023-11-08 02:23:46,False,216,190,160,70809,NaN,NaT,NaN,NaN,NaN
99,-170528132_5455590,0,2023-11-08 04:40:00,5455590,post,В Кузбассе нашли пивного фокусника. \n\nЖитель...,1,NaN,NaT,False,45,262,454,88255,45.0,2023-11-08 02:22:41,90.0,90.0,NaN

In [15]:
!python -m dostoevsky download fasttext-social-network-model

In [17]:
df["text"]

0     Алкоголь после кофе улучшает сон вечером и обе...
1     В Таиланде задержали мужчину из России, которы...
2                          Совет да любовь, так сказатб
3     Возьму 2-3 человека, которые хотят зарабатыват...
4     В России могут начать штрафовать родителей, чь...
                            ...
95    В России бездомных собак начнут кормить красно...
96    15-летний Адам Кадыров пришёл на награждение к...
97    Библиотеки в России выдают книги «иноагентов» ...
98    Глава Кабардино-Балкарии Казбек Коков вручил А...
99    В Кузбассе нашли пивного фокусника. \n\nЖитель...
Name: text, Length: 100, dtype: object

In [19]:
from dostoevsky.tokenization import RegexTokenizer
from dostoevsky.models import FastTextSocialNetworkModel

tokenizer = RegexTokenizer()
tokens = tokenizer.split('всё очень плохо')  # [('всё', None), ('очень', None), ('плохо', None)]

model = FastTextSocialNetworkModel(tokenizer=tokenizer)

messages = df["text"]

results = model.predict(messages, k=2)
sentiment_result = []
for message, sentiment in zip(messages, results):
    sentiment_result.append(sentiment)
pd.DataFrame(sentiment_result)

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

     neutral  negative      skip  positive
0   0.430157  0.355785       NaN       NaN
1   0.355785       NaN  0.201823       NaN
2   0.538993       NaN  0.058356       NaN
3   0.812877  0.140346       NaN       NaN
4   0.787941       NaN  0.177821       NaN
..       ...       ...       ...       ...
95  0.926314       NaN       NaN  0.085109
96  0.705795       NaN  0.092698       NaN
97  0.712242  0.115971       NaN       NaN
98  0.615098  0.182436       NaN       NaN
99  0.569863  0.294225       NaN       NaN

[100 rows x 4 columns]

In [33]:
dfs = pd.DataFrame(sentiment_result)
dfs["text"] = df["text"]
dfs[dfs["skip"].isna() & dfs["positive"]>=0.2]

,neutral,negative,skip,positive,text
6,0.651365,NaN,NaN,0.187143,Найден идеальный колпачок для зубной пасты. \n...
26,0.500010,NaN,NaN,0.191943,На ОГЭ 9-го класса по математике теперь официа...
28,0.341593,NaN,NaN,0.268951,Великолепная серия ножей от кузнеца из Нижнего...
32,0.724880,NaN,NaN,0.129413,ASMR для бати: Bosch выпустил адвент-календарь...
35,0.362979,NaN,NaN,0.173298,Нейронка оказалась настоящим гурманом.
36,0.577505,NaN,NaN,0.445540,Baldur's Gate 3 выбрали игрой года на церемони...
42,0.538993,NaN,NaN,0.191943,Забудь про банальные подарки!\n\nТрек-Пластинк...
45,0.743178,NaN,NaN,0.087574,"Не храни классные фото в телефоне, превращай и..."
54,0.461027,NaN,NaN,0.112805,Снизили цену на 40%! Всего на пару дней на мяг...
63,0.577505,NaN,NaN,0.129413,"Девушка поделилась схемой, как выучила английс..."
76,0.538993,NaN,NaN,0.187143,"Уволенная учительница из Миссура заявила, что ..."
77,0.803184,NaN,NaN,0.115971,Биткоин поднялся выше $37000
87,0.965910,NaN,NaN,0.082707,Трейлер Grand Theft Auto VI выйдет в начале де...
94,0.500010,NaN,NaN,0.187143,Забудь про банальные подарки!\n\nТрек-Пластинк...
95,0.926314,NaN,NaN,0.085109,В России бездомных собак начнут кормить красно...

In [4]:
df["owner"].value_counts()

owner
1    100
Name: count, dtype: int64

In [9]:
df = pd.json_normalize(f["posts"])
for i in ["date", "photo_date", "video_date"]
    df.loc[:, i] = pd.to_datetime(df[i], unit='s', origin='unix') 
df

KeyError: 'date'

In [3]:
f["posts"][1]["post_info"].keys()

dict_keys(['inner_type', 'donut', 'comments', 'marked_as_ads', 'short_text_rate', 'hash', 'type', 'date', 'from_id', 'id', 'likes', 'owner_id', 'post_type', 'reposts', 'text', 'views', 'owner', 'photo_text', 'photo_date'])

In [10]:
grabber.post_process(f["posts"][1]["post_info"])

{'inner_type': 'wall_wallpost',
 'donut': {'is_donut': False},
 'comments': {'count': 18},
 'marked_as_ads': 0,
 'short_text_rate': 0.8,
 'hash': 'T_x8KM4cmakDsUGluQ',
 'type': 'post',
 'attachments': [{'type': 'photo',
   'photo': {'album_id': -7,
    'date': 1699838054,
    'id': 457594444,
    'owner_id': -170528132,
    'access_key': '88fe3aa9c470c2388b',
    'post_id': 5467891,
    'sizes': [{'height': 58,
      'type': 'm',
      'width': 130,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=130x58&quality=96&sign=cba111d1eaa092fa61ff0896b3ae54fd&c_uniq_tag=sAxqKevKGduRhzcxNvfQGau-5xT-SsxTF-IjSzjFiiY&type=album'},
     {'height': 87,
      'type': 'o',
      'width': 130,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=130x87&quality=96&crop=176,0,717,480&sign=306459912336ae36c014926cfa2b75af&c_uniq_tag=H9kkyN0PKiUNfNo8v0Gl7eq_67zM_a9Hv-X1WrtHmmI&type=album'},
     {'height': 133,
      'type': 'p',
      'width': 200,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=200x133&quality=96&crop=174,0,722,480&sign=e926d6bfa7110ce3a64eeecde5511d49&c_uniq_tag=X8pIG3lw2ZEHY3YWwqwqi4pUBwNDHXn_gSt0pGhhiok&type=album'},
     {'height': 213,
      'type': 'q',
      'width': 320,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=320x213&quality=96&crop=174,0,721,480&sign=79dd134da6966281e9d8e14d355f511d&c_uniq_tag=XllVEwgrLlXXNj5lJ70DOlh4fDMx7pn3vp5yjtyLklU&type=album'},
     {'height': 340,
      'type': 'r',
      'width': 510,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=510x340&quality=96&crop=175,0,720,480&sign=6873dc61cd85c4f1fd533e5a5abbe7f8&c_uniq_tag=kpWLqGcZoe1EGcCOznz0VjokRLC9wVB42-gVeeHUx4s&type=album'},
     {'height': 34,
      'type': 's',
      'width': 75,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=75x34&quality=96&sign=ee395caaafacc7c64905957c2a913d29&c_uniq_tag=PLqXo5mNFoPDabL372LsCnCD55P5LxajuaRiuBWnmsM&type=album'},
     {'height': 271,
      'type': 'x',
      'width': 604,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=604x271&quality=96&sign=d133025ee7d8735bd28c1f74121286d3&c_uniq_tag=phV1rG5gEXbBIYiue7FP_CzO4bf26pbpw0lYQTTOLvw&type=album'},
     {'height': 362,
      'type': 'y',
      'width': 807,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=807x362&quality=96&sign=63e84a24c8b8c92b04885de9fbc6e26d&c_uniq_tag=FRsU-IaSUjSwzf_VdUhegrN9cF87ldEue43CqN3-Ri8&type=album'},
     {'height': 480,
      'type': 'z',
      'width': 1070,
      'url': 'https://sun9-48.userapi.com/impg/2akbWOvBblgvUM8MG5AiIdWEiRcwPnjJZeFUtg/wudZvlvYIDo.jpg?size=1070x480&quality=96&sign=49b618455551bb01b5a3794f8c7b93cd&c_uniq_tag=xP68cHxJRtratNjcH1vmxrUJC34k_a3f-7mAPXyL0Bo&type=album'}],
    'text': '',
    'user_id': 100,
    'web_view_token': '99a71ea9cae3a46b0b',
    'has_tags': False}}],
 'date': 1699858200,
 'from_id': -170528132,
 'id': 5467891,
 'likes': {'can_like': 0, 'count': 251, 'user_likes': 0},
 'owner_id': -170528132,
 'post_type': 'post',
 'reposts': {'count': 171},
 'text': 'Совет да любовь, так сказатб',
 'views': {'count': 38686},
 'owner': 1}

In [15]:

for p in f["posts"]:
    pinfo = p["post_info"]
    if (len(pinfo["attachments"]) == 0):

    for a in pinfo["attachments"]:
        print(a)

{'type': 'photo', 'photo': {'album_id': -7, 'date': 1699669870, 'id': 457594227, 'owner_id': -170528132, 'access_key': 'e9987759dab3cf446e', 'post_id': 5465204, 'sizes': [{'height': 73, 'type': 'm', 'width': 130, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=130x73&quality=96&sign=c40fb9b99da8b86990f9fd3aa09c178a&c_uniq_tag=ymDRgMIXN863SudMDs1xHQSUXbg4Y6XBpDqZ0Zk7KDY&type=album'}, {'height': 87, 'type': 'o', 'width': 130, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=130x87&quality=96&crop=102,0,1076,720&sign=e0634cf76949945caba1b88e4cce856b&c_uniq_tag=Xl0OyKP3gqB3zgF6sWbKT7_wwAkcyIuZahBorQM4eRc&type=album'}, {'height': 133, 'type': 'p', 'width': 200, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=200x133&quality=96&crop=98,0,1083,720&sign=fb38b9895e1573b3422b2087ee3446d8&c_uniq_tag=YFUb_0wJp2BsNK3rOEJAQZUuCe4aAdnrzC28k-eBYjk&type=album'}, {'height': 213, 'type': 'q', 'width': 320, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=320x213&quality=96&crop=99,0,1082,720&sign=7b863ca8d8f859bf2b9d5ef4997519ad&c_uniq_tag=udZE3LSnCbFfwMiBH_lhs8i3fRivje_R3CdbVkTjZ6o&type=album'}, {'height': 340, 'type': 'r', 'width': 510, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=510x340&quality=96&crop=100,0,1080,720&sign=2d72ee3ab420dc17fb675b5c754de6d0&c_uniq_tag=O1TycAltdqct7IIQUNX_d0vt9EWKQs8iRu38jVQ-oIM&type=album'}, {'height': 42, 'type': 's', 'width': 75, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=75x42&quality=96&sign=5881c3a1f3eee048074b49ba544d53f6&c_uniq_tag=SnuHzW-HVzJeyQSoW9w-v-V8FhETfPLA5pjWYv95PrE&type=album'}, {'height': 340, 'type': 'x', 'width': 604, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=604x340&quality=96&sign=fe605a65f924f2453bd72e24544ee427&c_uniq_tag=mFO3D4SgOL4VFMVGKnVmj-MMqson_jt4Dp_2IEt67Sc&type=album'}, {'height': 454, 'type': 'y', 'width': 807, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=807x454&quality=96&sign=ce6bbc8a48fe6b4786ecc0d4340d89ff&c_uniq_tag=2C-eYsyuh7GoKiUf-18QiBi6617VcqHBiPpcMAOoMGw&type=album'}, {'height': 720, 'type': 'z', 'width': 1280, 'url': 'https://sun9-20.userapi.com/impg/NWJis0YaUTrj52SoGp7yq_WNCQeQz32sndjmQA/FZgs-cFG2K0.jpg?size=1280x720&quality=96&sign=08771d0315b2999eff779592e0e09cc4&c_uniq_tag=MVYRYlJnQ_XVsv1A6ptMUHVenM2kB4ND203mbL7hiq8&type=album'}], 'text': '', 'user_id': 100, 'web_view_token': '031c9868844df232ef', 'has_tags': False}}
{'type': 'photo', 'photo': {'album_id': -7, 'date': 1699669410, 'id': 457594226, 'owner_id': -170528132, 'access_key': '7ef8acc1c6221796d3', 'post_id': 5465037, 'sizes': [{'height': 99, 'type': 'm', 'width': 130, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=130x99&quality=96&sign=0469d0c9f8dc8530a52f33d350c7d0f8&c_uniq_tag=tNEcd01OmiSWUKgtjXIwmEubtGzyXeH9OZjj49tsWNY&type=album'}, {'height': 99, 'type': 'o', 'width': 130, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=130x99&quality=96&sign=0469d0c9f8dc8530a52f33d350c7d0f8&c_uniq_tag=tNEcd01OmiSWUKgtjXIwmEubtGzyXeH9OZjj49tsWNY&type=album'}, {'height': 153, 'type': 'p', 'width': 200, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=200x153&quality=96&sign=e4743fc89ecd159bb9eeb66882c5daa1&c_uniq_tag=SkkupA62yGrgZs8kDNABYpQ-cCq7tz67ZtzmLGQvkx4&type=album'}, {'height': 244, 'type': 'q', 'width': 320, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=320x244&quality=96&sign=6597af916da4f8656d6243339b9a3dac&c_uniq_tag=fyiMrj03TZ9L6kfKEefF_cUlMKTWg2q8TJqIXPA7Tog&type=album'}, {'height': 389, 'type': 'r', 'width': 510, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=510x389&quality=96&sign=f062b8ab95a2b18c0e8e535c7d142a4c&c_uniq_tag=H1Nbw38CTSPow0sH3w5rdIKf74egAAkryEJTty7KPSY&type=album'}, {'height': 57, 'type': 's', 'width': 75, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=75x57&quality=96&sign=478f4f594695410eec44fba3dde49aeb&c_uniq_tag=BFb4pXFPRspdw3hejeiRD_a6P4UICDPepJzcN13KcwA&type=album'}, {'height': 439, 'type': 'x', 'width': 575, 'url': 'https://sun9-6.userapi.com/impg/TlIuHwb05zMwOtea8G2gAR4tMTVJA6mxKZA4_g/PnZmWfcdPnY.jpg?size=575x439&quality=96&sign=9d9f4e585b8a945283d4c245e26f9bae&c_uniq_tag=VPvLCPeBpi7oag9rquvvrSofy70i-wkVauanv7aIoew&type=album'}], 'text': '', 'user_id': 100, 'web_view_token': '0bed48ae1a9c0cf753', 'has_tags': False}}
{'type': 'video', 'video': {'response_type': 'full', 'access_key': '5366292494adb80f95', 'can_like': 1, 'can_repost': 1, 'can_subscribe': 1, 'can_add_to_faves': 0, 'can_add': 1, 'comments': 13, 'date': 1699669384, 'description': '', 'duration': 44, 'image': [{'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_s', 'width': 130, 'height': 96, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_m', 'width': 160, 'height': 120, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_l', 'width': 320, 'height': 240, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_x', 'width': 800, 'height': 450, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_w', 'width': 720, 'height': 720}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_t', 'width': 320, 'height': 320}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=2&type=39&tkn=WQfOxxVRZ9yJDjYlRx4_eWBlO78&fn=vid_u', 'width': 720, 'height': 720}], 'first_frame': [{'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=0&type=39&tkn=hNOkj7_fMYQHNke6Eq8sCQhH6_0&fn=vid_f', 'width': 405, 'height': 405}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=0&type=39&tkn=hNOkj7_fMYQHNke6Eq8sCQhH6_0&fn=vid_md', 'width': 270, 'height': 270}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=0&type=39&tkn=hNOkj7_fMYQHNke6Eq8sCQhH6_0&fn=vid_d', 'width': 135, 'height': 135}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=0&type=39&tkn=hNOkj7_fMYQHNke6Eq8sCQhH6_0&fn=vid_sm', 'width': 72, 'height': 72}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5631741069868&idx=0&type=39&tkn=hNOkj7_fMYQHNke6Eq8sCQhH6_0&fn=vid_w', 'width': 720, 'height': 720}], 'width': 720, 'height': 720, 'id': 456280021, 'owner_id': -170528132, 'title': 'Video by Топор — горячие новости', 'track_code': 'video_66764fcdDm6SS7_ftRv92Lg9SG5W4kxxG5sjk1kmuZN7nHas4CI9T41CudyydvDdvTsgbFHUfkkrqxGiXVHY_xecZIHRFQ16vw', 'type': 'video', 'views': 28473, 'local_views': 28473, 'can_dislike': 1}}
{'type': 'video', 'video': {'response_type': 'full', 'access_key': 'dbfa30dd6c6b8083a6', 'can_like': 1, 'can_repost': 1, 'can_subscribe': 1, 'can_add_to_faves': 0, 'can_add': 1, 'comments': 88, 'date': 1699669371, 'description': '', 'duration': 68, 'image': [{'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_s', 'width': 130, 'height': 96, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_m', 'width': 160, 'height': 120, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_l', 'width': 320, 'height': 240, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_x', 'width': 800, 'height': 450, 'with_padding': 1}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_w', 'width': 1280, 'height': 704}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_t', 'width': 320, 'height': 176}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=13&type=39&tkn=6J6SUYrqJAQFAw9Ac7Pcq_VpXtI&fn=vid_u', 'width': 720, 'height': 396}], 'first_frame': [{'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=0&type=39&tkn=-y298xX9RrHJoNr1W71ci0m1bIs&fn=vid_f', 'width': 720, 'height': 405}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=0&type=39&tkn=-y298xX9RrHJoNr1W71ci0m1bIs&fn=vid_md', 'width': 480, 'height': 270}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=0&type=39&tkn=-y298xX9RrHJoNr1W71ci0m1bIs&fn=vid_d', 'width': 240, 'height': 135}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=0&type=39&tkn=-y298xX9RrHJoNr1W71ci0m1bIs&fn=vid_sm', 'width': 128, 'height': 72}, {'url': 'https://i.mycdn.me/getVideoPreview?id=5368300243682&idx=0&type=39&tkn=-y298xX9RrHJoNr1W71ci0m1bIs&fn=vid_w', 'width': 1280, 'height': 720}], 'width': 640, 'height': 352, 'id': 456280020, 'owner_id': -170528132, 'title': 'Video by Топор — горячие новости', 'track_code': 'video_99e71e89AJkbcD5SkxL9a0mRg3D9OPTtUcnd33gsyKZ-o6jiiSYzuAR5OFGUf_BuTJfocPgOxtVh-e_vfFupyhKjus-4EQONNg', 'type': 'video', 'views': 25248, 'local_views': 25248, 'can_dislike': 1}}
{'type': 'photo', 'photo': {'album_id': -7, 'date': 1699669351, 'id': 457594217, 'owner_id': -170528132, 'access_key': 'cd45db4b0c6bf7d6bd', 'sizes': [{'height': 87, 'type': 'm', 'width': 130, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=130x87&quality=96&sign=c09e9d8434ddecf3a5a9b5c7737ac84b&c_uniq_tag=7nEytskVwA8gxFDmRpp3T_lmkub5v3HC2HpljJZlNsg&type=album'}, {'height': 87, 'type': 'o', 'width': 130, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=130x87&quality=96&sign=c09e9d8434ddecf3a5a9b5c7737ac84b&c_uniq_tag=7nEytskVwA8gxFDmRpp3T_lmkub5v3HC2HpljJZlNsg&type=album'}, {'height': 133, 'type': 'p', 'width': 200, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=200x133&quality=96&sign=b64dc0a8f8feb13e380961946e33bc8f&c_uniq_tag=iJ5B8PC3QI_isPiglCAMO1Fv7thb7WtgO4JAhX8ig3k&type=album'}, {'height': 213, 'type': 'q', 'width': 320, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=320x213&quality=96&sign=4aa98819bfb87a96edcac7fca808b823&c_uniq_tag=3bJZcy0ryBl-wG2ne0yfu8mlllmA0t1V9vKXDZn342M&type=album'}, {'height': 340, 'type': 'r', 'width': 510, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=510x340&quality=96&sign=74a9d55b6d352ec8b1864857264d0c55&c_uniq_tag=s5CW3TM4QLNkexK78vq9f5AOxvM7YfKibJWIpyEf98U&type=album'}, {'height': 50, 'type': 's', 'width': 75, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=75x50&quality=96&sign=cefc6de48568d935e93ce17fb5fd38a9&c_uniq_tag=KhQ4LfkoMt69O31pLIMP24esW11G1wu-RsV-5tBJWkk&type=album'}, {'height': 402, 'type': 'x', 'width': 604, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=604x402&quality=96&sign=dbb8d79451b115be48713ad725972cc5&c_uniq_tag=5Ojc112fJQTlNA3tpR9loo3VJ9XsnmHclpFdyJr85K8&type=album'}, {'height': 538, 'type': 'y', 'width': 807, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=807x538&quality=96&sign=d57f2b9af4c74c93affb252e51563400&c_uniq_tag=B6vTzWA6s432fLFNeXE6noAo07c5tDw9sFhYJnoJ9CU&type=album'}, {'height': 853, 'type': 'z', 'width': 1280, 'url': 'https://sun9-57.userapi.com/impg/IpKabwLo_TU8MLf5iL8W7PBxPrws5Gol53LITQ/DaqfmwUxBUo.jpg?size=1280x853&quality=96&sign=de10b78ce64181c34a77870926c5b342&c_uniq_tag=fUrXKDlGRLjSR6Kx6Eh8EnSZLI9wPJgmFntQagKxkWY&type=album'}], 'text': '', 'user_id': 100, 'web_view_token': '621b7d2b3c96a0ab6d', 'has_tags': False}}
{'type': 'photo', 'photo': {'album_id': -7, 'date': 1699669351, 'id': 457594218, 'owner_id': -170528132, 'access_key': 'd3bbe5ee10925f8952', 'sizes': [{'height': 87, 'type': 'm', 'width': 130, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=130x87&quality=96&sign=d83653ba2e4edfb13e85272f34f266bd&c_uniq_tag=-OsvCjav0sdg4uYyZGCfIKg8h-hdJp8A6B2i2HeI5ZU&type=album'}, {'height': 87, 'type': 'o', 'width': 130, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=130x87&quality=96&sign=d83653ba2e4edfb13e85272f34f266bd&c_uniq_tag=-OsvCjav0sdg4uYyZGCfIKg8h-hdJp8A6B2i2HeI5ZU&type=album'}, {'height': 133, 'type': 'p', 'width': 200, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=200x133&quality=96&sign=f34ad87d09f36eda9e5f53cb3399d676&c_uniq_tag=6Gp4ce-xfeV3PKHMr7DIzfVyuB_TsUKOyEGotB3-SVc&type=album'}, {'height': 213, 'type': 'q', 'width': 320, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=320x213&quality=96&sign=ea0fb84ec236ccdb1da19d057073b6d8&c_uniq_tag=ojq1HXYWomMhsz-rfOfYratDUAoVX_oQ0YZWIPdUcaE&type=album'}, {'height': 340, 'type': 'r', 'width': 510, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=510x340&quality=96&sign=3841b6db0160958d54e88052f7986564&c_uniq_tag=8btlHhopVMV9oiWYEbCYEuCSsMfPQR-7_Y4AgAwIW2Y&type=album'}, {'height': 50, 'type': 's', 'width': 75, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=75x50&quality=96&sign=8bf052169fe0a42360f2d32acf7f633b&c_uniq_tag=1DNWdJsbrC611R6n9ynLskP6nZOJ5zHCM6pGjQbyJmY&type=album'}, {'height': 402, 'type': 'x', 'width': 604, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=604x402&quality=96&sign=cda0ef482ee9eba16e6e410c57a72149&c_uniq_tag=ubmXd62hLEdDH02Gh3htIcTKhPGSuWW2mYcxG-hkP7c&type=album'}, {'height': 538, 'type': 'y', 'width': 807, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=807x538&quality=96&sign=8cd39230616411db33123024760de58f&c_uniq_tag=iziaMmx3Wx0f27SZCBPmtcMVEDqo2JAWD5RKLaK2WAw&type=album'}, {'height': 853, 'type': 'z', 'width': 1280, 'url': 'https://sun9-44.userapi.com/impg/_yUMV12nfeqK3Th1ivX_6ev5HZlljCsqr0ZznQ/zqVTfLba6Ds.jpg?size=1280x853&quality=96&sign=5bee548bc210b0450bb8458fbef3ddc7&c_uniq_tag=KQiJlkdTh6Ci0A8wWJLfmZeJmPFvWYyMSZVDOAzdblM&type=album'}], 'text': '', 'user_id': 100, 'web_view_token': 'bbf41a6ca17cee588c', 'has_tags': False}}
{'type': 'photo', 'photo': {'album_id': -7, 'date': 1699669351, 'id': 457594219, 'owner_id': -170528132, 'access_key': 'dff0efdb5f9b828884', 'sizes': [{'height': 87, 'type': 'm', 'width': 130, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=130x87&quality=96&sign=bea784892e8e141a06d8416ab982e91c&c_uniq_tag=xqc_Pc7kjZ0yzok_kYXItjG96RqX_fs-UhuemCYm4_w&type=album'}, {'height': 87, 'type': 'o', 'width': 130, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=130x87&quality=96&sign=bea784892e8e141a06d8416ab982e91c&c_uniq_tag=xqc_Pc7kjZ0yzok_kYXItjG96RqX_fs-UhuemCYm4_w&type=album'}, {'height': 133, 'type': 'p', 'width': 200, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=200x133&quality=96&sign=195d80dedf23b1a94d1b5520bc578762&c_uniq_tag=n9urip45_JIZrV8MPo6rF0Je4PiOSdDAe4nYb28HSq0&type=album'}, {'height': 213, 'type': 'q', 'width': 320, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=320x213&quality=96&sign=aa2da1a10c396d510e248e329a50ac11&c_uniq_tag=Lfg4XtLKxqJipoK0j1z4luHhOP2TEyur2rYCJH-nlB8&type=album'}, {'height': 340, 'type': 'r', 'width': 510, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=510x340&quality=96&sign=e5f530b6c182a25b6cc69ffb0dbdaffa&c_uniq_tag=TKxV-p1WZSYJisu91YQfB8pNSwd9IJorDwCTkAdnT7w&type=album'}, {'height': 50, 'type': 's', 'width': 75, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=75x50&quality=96&sign=0012811df4f07f7a4b8432971bc786da&c_uniq_tag=r-DNY5SZwh_H1pgqb0rJNusIqyC7TbrhCLtfqYT_Jzs&type=album'}, {'height': 402, 'type': 'x', 'width': 604, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=604x402&quality=96&sign=6eb95fdaccd51c66f6ded65c198ec1f3&c_uniq_tag=aXQzg4GGEXIIm76UMVaw2oXlx5LQmznaq4xtK9pabKI&type=album'}, {'height': 538, 'type': 'y', 'width': 807, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=807x538&quality=96&sign=8ce041b8497bd7675a23ff094cf60638&c_uniq_tag=rsNvgUdaN0VME4uVTquqD_irM0eXC0ezC9cQ6hB4N24&type=album'}, {'height': 853, 'type': 'z', 'width': 1280, 'url': 'https://sun9-7.userapi.com/impg/IQ-2o29-NTnTTh2F96YL67-tSAMvSQDEfMgF0w/m4Ii3wHLXHo.jpg?size=1280x853&quality=96&sign=6465d793105835aa832ebdb6bfd4a05b&c_uniq_tag=k51b1NwsmjkUWCM6Kk2jf8jAYeOJEAph_Cc_7-J5DhM&type=album'}], 'text': '', 'user_id': 100, 'web_view_token': 'f03f3e74707ca6e29f', 'has_tags': False}}

In [9]:
pd.json_normalize(f["posts"])

,post_id,post_info.inner_type,post_info.donut.is_donut,post_info.comments.count,post_info.marked_as_ads,post_info.short_text_rate,post_info.hash,post_info.type,post_info.attachments,post_info.date,...,post_info.id,post_info.likes.can_like,post_info.likes.count,post_info.likes.user_likes,post_info.owner_id,post_info.post_type,post_info.reposts.count,post_info.text,post_info.views.count,post_info.carousel_offset
0,-1705281325465204,wall_wallpost,False,4,0,0.8,phIy7YuYObd93EkeFA,post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",1699725601,...,5465204,0,1,0,-170528132,post,4,Baldur's Gate 3 выбрали игрой года на церемони...,2879,NaN
1,-1705281325465037,wall_wallpost,False,23,0,0.8,cqewWEW4lLwBE0Z76w,post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",1699722001,...,5465037,0,61,0,-170528132,post,73,Брендовая одежда в России подорожает до 50% пе...,19555,NaN
2,-1705281325464762,wall_wallpost,False,13,0,0.8,S3-pIAOowMyA7ineNQ,post,"[{'type': 'video', 'video': {'response_type': ...",1699716600,...,5464762,0,65,0,-170528132,post,17,В Уфе ворона запуталась и провисела в воздухе ...,28714,NaN
3,-1705281325464440,wall_wallpost,False,88,0,0.8,Pu3hoP6OcTPr4msqiA,post,"[{'type': 'video', 'video': {'response_type': ...",1699711202,...,5464440,0,50,0,-170528132,post,48,"Российский депутат назвал женщин, рожающих пос...",26588,NaN
4,-1705281325464254,wall_wallpost,False,30,0,0.8,UJJ_U6uE4jNmAKoACQ,post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",1699707300,...,5464254,0,39,0,-170528132,post,45,Новосибирские египтяне построили дворец Клеопа...,24992,0.0
5,-1705281325463919,wall_wallpost,False,339,0,0.8,ohkaiHl7r8KI18pO_Q,post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",1699703700,...,5463919,0,103,0,-170528132,post,79,В Госдуме предложили создать свой интернет для...,38339,NaN
6,-1705281325463745,wall_wallpost,False,3,1,0.8,sRYkU2BoVozuAVr2-w,post,"[{'type': 'photo', 'photo': {'album_id': -51, ...",1699700100,...,5463745,0,6,0,-170528132,post,3,Забудь про банальные подарки!\n\nТрек-Пластинк...,39598,0.0
7,-1705281325463659,wall_wallpost,False,37,0,0.8,lgB3pQOXXN-f5MqCug,post,"[{'type': 'video', 'video': {'response_type': ...",1699698600,...,5463659,0,513,0,-170528132,post,568,"Отправь в рабочий чат, пусть коллеги порадуются.",65039,NaN
8,-1705281325463527,wall_wallpost,False,153,0,0.8,EPrPPKs2yxJo1YxinQ,post,"[{'type': 'photo', 'photo': {'album_id': -7, '...",1699696200,...,5463527,0,305,0,-170528132,post,717,Сильный шторм на Солнце может отключить интерн...,44198,NaN
9,-1705281325463356,wall_wallpost,False,4,1,0.8,7D7Ww12Y-wv-HioBjQ,post,"[{'type': 'photo', 'photo': {'album_id': -51, ...",1699692600,...,5463356,0,4,0,-170528132,post,0,"Не храни классные фото в телефоне, превращай и...",23340,0.0

In [107]:
df = json.load(open("data/user_info.json","r",encoding='utf-8'))["user_info"]
df = pd.json_normalize(df)

In [113]:
df["id"].nunique()

2489

In [98]:
df = df.drop(columns=["can_access_closed", 
                      "personal", 
                      "has_photo",
                      "",
                      "relation_partner.id", 
                      'relation_partner.first_name', 
                      'relation_partner.last_name'])

KeyError: "['can_access_closed', 'personal', 'relation_partner.id', 'relation_partner.first_name', 'relation_partner.last_name'] not found in axis"

In [86]:
df.loc[~pd.isna(df["relation"]) & (df["relation"]==0), "relation"] = None

In [94]:
col = "personal.people_main"
df[~pd.isna(df[col])][col].value_counts()

personal.people_main
0.0    32
2.0     6
5.0     3
1.0     2
6.0     1
Name: count, dtype: int64

In [88]:
df

,id,bdate,has_photo,has_mobile,followers_count,sex,verified,friend_status,first_name,last_name,...,counters.clips,counters.clips_views,counters.clips_likes,counters.posts,skype,personal.political,personal.religion,counters.articles,twitter,personal.religion_id
0,6152705,8.3.1965,1,1,136.0,1,0,0,Ekaterina,Zaderieva,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,136014858,30.7.2002,1,1,622.0,1,0,0,Alisa,Boyarkina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,710431761,11.3.2008,1,1,14.0,1,0,0,Byka,Bybyby,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,50867218,30.9,1,1,465.0,2,0,0,Alexey,Novikov,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,65948699,6.4,1,1,936.0,2,0,0,Danila,Potsenkovsky,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,330745,22.8.1985,1,1,NaN,1,0,0,Olga,Polyakova,...,NaN,NaN,NaN,177.0,NaN,NaN,NaN,NaN,NaN,NaN
156,170808314,22.6,1,1,1249.0,1,0,0,Viktoria,Vavilova,...,NaN,NaN,NaN,NaN,vkravz,NaN,NaN,NaN,NaN,NaN
157,58423803,14.10,1,1,579.0,2,0,0,Egor,Trufanov,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,126338556,14.10.1998,1,1,1781.0,1,0,0,Anastasia,Gerasimova,...,NaN,NaN,NaN,NaN,NaN,NaN,Православие,1.0,NaN,102.0
159,125439,10.6,1,1,1102.0,2,0,0,Danil,Krutskikh,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
def bdate_year_parser(bday):
    if pd.isna(bday):
        return None
    bday = bday.split(".")
    if len(bday) == 3:
        return pd.to_datetime(".".join(bday), format="%d.%m.%Y")
    else:
        return None
df["bdate"].apply(bdate_year_parser)

0     1965-03-08
1     2002-07-30
2     2008-03-11
3            NaT
4            NaT
         ...
155   1985-08-22
156          NaT
157          NaT
158   1998-10-14
159          NaT
Name: bdate, Length: 160, dtype: datetime64[ns]

In [90]:
df["bdate"] = df["bdate"].apply(bdate_year_parser)

In [91]:
now = pd.to_datetime('now')
df['age'] = (now.year - df['bdate'].dt.year) - ((now.month - df['bdate'].dt.month) < 0)

In [103]:
df = df.drop(columns=["friend_status"])

In [104]:
df

,id,bdate,followers_count,sex,verified,first_name,last_name,is_closed,city.id,city.title,...,counters.clips_views,counters.clips_likes,counters.posts,skype,personal.political,personal.religion,counters.articles,twitter,personal.religion_id,age
0,6152705,1965-03-08,136.0,1,0,Ekaterina,Zaderieva,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0
1,136014858,2002-07-30,622.0,1,0,Alisa,Boyarkina,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0
2,710431761,2008-03-11,14.0,1,0,Byka,Bybyby,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0
3,50867218,NaT,465.0,2,0,Alexey,Novikov,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,65948699,NaT,936.0,2,0,Danila,Potsenkovsky,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,330745,1985-08-22,NaN,1,0,Olga,Polyakova,True,2.0,Saint Petersburg,...,NaN,NaN,177.0,NaN,NaN,NaN,NaN,NaN,NaN,38.0
156,170808314,NaT,1249.0,1,0,Viktoria,Vavilova,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,vkravz,NaN,NaN,NaN,NaN,NaN,NaN
157,58423803,NaT,579.0,2,0,Egor,Trufanov,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,126338556,1998-10-14,1781.0,1,0,Anastasia,Gerasimova,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,Православие,1.0,NaN,102.0,25.0
159,125439,NaT,1102.0,2,0,Danil,Krutskikh,False,2.0,Saint Petersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.drop(['skype', 'twitter',

In [105]:
df.columns

Index(['id', 'bdate', 'followers_count', 'sex', 'verified', 'first_name',
       'last_name', 'is_closed', 'city.id', 'city.title', 'country.id',
       'country.title', 'occupation.id', 'occupation.name', 'occupation.type',
       'occupation.graduate_year', 'occupation.country_id',
       'occupation.city_id', 'counters.albums', 'counters.audios',
       'counters.followers', 'counters.pages', 'counters.photos',
       'counters.subscriptions', 'counters.videos', 'counters.video_playlists',
       'counters.clips_followers', 'interests', 'books', 'tv', 'games',
       'movies', 'activities', 'music', 'career', 'military', 'university',
       'university_name', 'faculty', 'faculty_name', 'graduation', 'home_town',
       'relation', 'universities', 'schools', 'relatives', 'personal.alcohol',
       'personal.inspired_by', 'personal.langs', 'personal.langs_full',
       'personal.life_main', 'personal.people_main', 'personal.smoking',
       'education_form', 'counters.groups', 'education_status',
       'counters.gifts', 'counters.clips', 'counters.clips_views',
       'counters.clips_likes', 'counters.posts', 'skype', 'personal.political',
       'personal.religion', 'counters.articles', 'twitter',
       'personal.religion_id', 'age'],
      dtype='object')

In [53]:
to_drop = []
for j in df.columns:
    if (df[j].isna().all()):
        print(j)

In [55]:
to_drop = []
for j in df.columns:
    if (df[j].value_counts().shape[0]==1):
        print(j)

has_mobile
blacklisted
blacklisted_by_me
is_hidden_from_feed
friend_status
crop_photo.photo.album_id
crop_photo.photo.text
crop_photo.photo.has_tags
online_mobile
personal
status_audio.artist
status_audio.id
status_audio.owner_id
status_audio.title
status_audio.duration
status_audio.is_explicit
status_audio.is_focus_track
status_audio.track_code
status_audio.url
status_audio.stream_duration
status_audio.date
status_audio.main_artists
status_audio.short_videos_allowed
status_audio.stories_allowed
status_audio.stories_cover_allowed

In [28]:
data = json.load(open("user_info.json", "r"))["users_likes"]
data_for_df = []
for i in data:
    data_for_df.extend(list(zip([i]*len(data[i]), map(str, data[i]))))
data_for_df

[('55750', '815362636'),
 ('55750', '120924785'),
 ('55750', '447424684'),
 ('55750', '170808314'),
 ('55750', '91353123'),
 ('55750', '126338556'),
 ('55750', '489217298'),
 ('55750', '279043178'),
 ('55750', '268430097'),
 ('55750', '347156076'),
 ('55750', '196095965'),
 ('55750', '638912159'),
 ('55750', '332224693'),
 ('55750', '356277235'),
 ('55750', '146427005'),
 ('55750', '299292594'),
 ('55750', '176881599'),
 ('55750', '332696791'),
 ('55750', '224594876'),
 ('55750', '515756155'),
 ('55750', '485120158'),
 ('55750', '138446566'),
 ('55750', '31065326'),
 ('55750', '249571811'),
 ('55750', '218910388'),
 ('55750', '6371'),
 ('55750', '46214'),
 ('55750', '74392'),
 ('55750', '125439'),
 ('55750', '177311'),
 ('55750', '330745'),
 ('55750', '482895'),
 ('55750', '546612'),
 ('55750', '617688'),
 ('55750', '769957'),
 ('55750', '1548422'),
 ('55750', '2070090'),
 ('55750', '2240973'),
 ('55750', '2448445'),
 ('55750', '2714695'),
 ('55750', '2874359'),
 ('55750', '2930269'),
 ('55750', '2970426'),
 ('55750', '3461247'),
 ('55750', '3621236'),
 ('55750', '3675039'),
 ('55750', '3676059'),
 ('55750', '4765850'),
 ('55750', '5882611'),
 ('55750', '6152705'),
 ('55750', '7098919'),
 ('55750', '7108139'),
 ('55750', '7415724'),
 ('55750', '7661338'),
 ('55750', '8009431'),
 ('55750', '8069449'),
 ('55750', '10375032'),
 ('55750', '11591755'),
 ('55750', '11734757'),
 ('55750', '12396744'),
 ('55750', '12928384'),
 ('55750', '15595769'),
 ('55750', '16745752'),
 ('55750', '17630487'),
 ('55750', '18140058'),
 ('55750', '21798320'),
 ('55750', '23088171'),
 ('55750', '24278088'),
 ('55750', '25448886'),
 ('55750', '26305326'),
 ('55750', '28518366'),
 ('55750', '29039694'),
 ('55750', '29076461'),
 ('55750', '30739440'),
 ('55750', '31314562'),
 ('55750', '31396775'),
 ('55750', '31746367'),
 ('55750', '31795984'),
 ('55750', '32039088'),
 ('55750', '32312530'),
 ('55750', '32518617'),
 ('55750', '34323679'),
 ('55750', '34683674'),
 ('55750', '36568857'),
 ('55750', '38183149'),
 ('55750', '39235243'),
 ('55750', '40694836'),
 ('55750', '40767810'),
 ('55750', '41364631'),
 ('55750', '50609713'),
 ('55750', '50867218'),
 ('55750', '52214093'),
 ('55750', '52709986'),
 ('55750', '53743549'),
 ('55750', '60753377'),
 ('55750', '60858807'),
 ('55750', '62197226'),
 ('55750', '62449311'),
 ('55750', '65321720'),
 ('55750', '65948699'),
 ('56623', '815362636'),
 ('56623', '215381931'),
 ('56623', '62449311'),
 ('56623', '249953241'),
 ('56623', '13631376'),
 ('56623', '155238333'),
 ('56623', '266851580'),
 ('56621', '177599'),
 ('56621', '628114'),
 ('56621', '236437161'),
 ('56621', '250345824'),
 ('56621', '536888331'),
 ('56621', '132907747'),
 ('56621', '685415978'),
 ('56621', '100426233'),
 ('56621', '4411590'),
 ('56621', '653141341'),
 ('56621', '141399482'),
 ('56621', '196831349'),
 ('56621', '132930861'),
 ('56621', '8574436'),
 ('56621', '13815733'),
 ('56621', '83945480'),
 ('56621', '271593797'),
 ('56621', '136371753'),
 ('56621', '211192353'),
 ('56621', '208856398'),
 ('56621', '33700553'),
 ('56621', '515048560'),
 ('56621', '345605246'),
 ('56621', '177029567'),
 ('56621', '91627257'),
 ('56621', '91907990'),
 ('56621', '189911714'),
 ('56621', '807207156'),
 ('56621', '134771299'),
 ('56621', '208647804'),
 ('56621', '2643031'),
 ('56621', '152416966'),
 ('56621', '240746064'),
 ('56621', '3676059'),
 ('56621', '591518546'),
 ('56621', '400266298'),
 ('56621', '7007438'),
 ('56621', '123645967'),
 ('56621', '1397481'),
 ('56621', '240617983'),
 ('56621', '2413525'),
 ('56621', '30617736'),
 ('56621', '136916'),
 ('56621', '31795984'),
 ('56621', '33979484'),
 ('56621', '41144145'),
 ('56621', '245521273'),
 ('56621', '586271927'),
 ('56621', '222651136'),
 ('56621', '2974332'),
 ('56621', '275042427'),
 ('56621', '206910367'),
 ('56621', '319307405'),
 ('56621', '10208826'),
 ('56621', '96514529'),
 ('56621', '74974397'),
 ('56621', '31427931'),
 ('56621', '245709217'),
 ('56621', '175825897'),
 ('56621', '138446566'),
 ('56621', '353345497'),
 ('56621', '157576131'),
 ('56621', '558984534'),
 ('56621', '14130'),
 ('56621', '431102690'),
 ('56621', '763530412'),
 ('56621', '20199180'),
 ('56621', '559085174'),
 ('56621', '462468262'),
 ('56621', '217271328'),
 ('56621', '264605991'),
 ('56621', '8905788'),
 ('56621', '769896244'),
 ('56621', '5133461'),
 ('56621', '14592163'),
 ('56621', '709322365'),
 ('56621', '104382647'),
 ('56621', '256335274'),
 ('56621', '336610200'),
 ('56621', '769138030'),
 ('56621', '439774598'),
 ('56621', '249953241'),
 ('56621', '145157781'),
 ('56621', '356599570'),
 ('56621', '197044180'),
 ('56621', '380845543'),
 ('56621', '246184851'),
 ('56621', '383501067'),
 ('56621', '89417157'),
 ('56621', '65020531'),
 ('56621', '132460094'),
 ('56621', '421101608'),
 ('56621', '161107581'),
 ('56621', '11312216'),
 ('56621', '2070090'),
 ('56621', '52214093'),
 ('56621', '4951128'),
 ('56621', '7021704'),
 ('56621', '201814463'),
 ('56621', '565922085'),
 ('56619', '157755263'),
 ('56619', '145157781'),
 ('56619', '544957186'),
 ('56619', '379987985'),
 ('56619', '56380224'),
 ('56619', '266851580'),
 ('56619', '744054487'),
 ('56619', '179215256'),
 ('56619', '297526820'),
 ('56619', '81516676'),
 ('56619', '3461247'),
 ('56619', '559158166'),
 ('56619', '50012236'),
 ('56619', '233405583'),
 ('56619', '53137703'),
 ('56619', '3355905'),
 ('56619', '62449311'),
 ('56619', '155238333'),
 ('56619', '104382647'),
 ('56619', '165399992'),
 ('56619', '555304430'),
 ('56619', '67628323'),
 ('56616', '815362636'),
 ('56616', '50012236'),
 ('56616', '638912159'),
 ('56616', '680089470'),
 ('56616', '622680110'),
 ('56616', '383501067'),
 ('56616', '41144145'),
 ('56616', '266851580'),
 ('56616', '538161678'),
 ('56616', '250345824'),
 ('56616', '503920129'),
 ('56616', '60858807'),
 ('56616', '546612'),
 ('56616', '3461247'),
 ('56616', '155238333'),
 ('56616', '658239405'),
 ('56616', '803126561'),
 ('56616', '616076869'),
 ('56616', '2448445'),
 ('56614', '266851580'),
 ('56614', '401402807'),
 ('56614', '240617983'),
 ('56614', '380845543'),
 ('56614', '546612'),
 ('56614', '379987985'),
 ('56614', '538161678'),
 ('56614', '589370912'),
 ('56614', '250345824'),
 ('56614', '63299349'),
 ('56614', '656404297'),
 ('56614', '652799516'),
 ('56614', '110614380'),
 ('56614', '523364962'),
 ('56614', '625887544'),
 ('56614', '170229946'),
 ('56614', '563827481'),
 ('56614', '155238333'),
 ('56614', '13568580'),
 ('56614', '3355905'),
 ('56614', '2448445'),
 ('56614', '555304430'),
 ('56614', '3461247'),
 ('56614', '18239'),
 ('56614', '84006'),
 ('56610', '1548422'),
 ('56610', '330171503'),
 ('56610', '437737411'),
 ('56610', '347233720'),
 ('56610', '3725511'),
 ('56610', '2874359'),
 ('56610', '184594037'),
 ('56610', '266851580'),
 ('56610', '380845543'),
 ('56610', '700863813'),
 ('56610', '546612'),
 ('56610', '746858397'),
 ('56610', '133867554'),
 ('56610', '683136923'),
 ('56610', '512437676'),
 ('56610', '51172100'),
 ('56610', '23055768'),
 ('56610', '749816684'),
 ('56610', '605464950'),
 ('56610', '138446566'),
 ('56610', '693454302'),
 ('56610', '174536949'),
 ('56610', '328882619'),
 ('56610', '813036459'),
 ('56610', '96264188'),
 ('56610', '152400994'),
 ('56610', '523364962'),
 ('56610', '3676059'),
 ('56610', '3461247'),
 ('56610', '329216338'),
 ('56610', '594567825'),
 ('56610', '243968204'),
 ('56610', '240617983'),
 ('56610', '367057989'),
 ('56610', '478376772'),
 ('56610', '250345824'),
 ('56610', '257688696'),
 ('56610', '125293009'),
 ('56610', '68069742'),
 ('56610', '589370912'),
 ('56610', '100448063'),
 ('56610', '51258642'),
 ('56610', '320314406'),
 ('56610', '2070090'),
 ('56610', '104382647'),
 ('56610', '658239405'),
 ('56610', '155238333'),
 ('56609', '266851580'),
 ('56609', '546612'),
 ('56609', '240617983'),
 ('56609', '485476881'),
 ('56609', '129102705'),
 ('56609', '138960638'),
 ('56609', '46214'),
 ('56609', '601128519'),
 ('56609', '98241834'),
 ('56609', '812860671'),
 ('56609', '281365134'),
 ('56609', '589370912'),
 ('56609', '79395306'),
 ('56609', '750792547'),
 ('56609', '462468262'),
 ('56609', '155238333'),
 ('56609', '624254288'),
 ('56609', '538161678'),
 ('56609', '639455852'),
 ('56609', '658239405'),
 ('56607', '266851580'),
 ('56607', '546612'),
 ('56607', '24447996'),
 ('56607', '433201375'),
 ('56607', '51354997'),
 ('56607', '2448445'),
 ('56607', '279858970'),
 ('56607', '313718703'),
 ('56607', '2070090'),
 ('56607', '688934506'),
 ('56607', '230303103'),
 ('56607', '586271927'),
 ('56607', '3437273'),
 ('56607', '538161678'),
 ('56607', '249953241'),
 ('56607', '170229946'),
 ('56607', '472257317'),
 ('56607', '3461247'),
 ('56607', '2886043'),
 ('56607', '381592445'),
 ('56607', '377843265'),
 ('56607', '232706689'),
 ('56607', '138072354'),
 ('56607', '197044180'),
 ('56607', '98269555'),
 ('56607', '601128519'),
 ('56607', '401402807'),
 ('56607', '284476179'),
 ('56607', '155238333'),
 ('56607', '495682417'),
 ('56607', '6371'),
 ('56607', '169979821'),
 ('56607', '275072576'),
 ('56607', '1250176'),
 ('56607', '18239'),
 ('56607', '227598651'),
 ('56607', '62449311'),
 ('56607', '14130'),
 ('56607', '524022643'),
 ('56607', '31746367'),
 ('56607', '139669455'),
 ('56607', '449346017'),
 ('56607', '136530114'),
 ('56607', '165058781'),
 ('56604', '1548422'),
 ('56604', '743431852'),
 ('56604', '680089470'),
 ('56604', '235162042'),
 ('56604', '252015299'),
 ('56604', '266851580'),
 ('56604', '3355905'),
 ('56604', '567707546'),
 ('56604', '546612'),
 ('56604', '544957186'),
 ('56604', '7999223'),
 ('56604', '50873509'),
 ('56604', '105567320'),
 ('56604', '664210024'),
 ('56604', '623839158'),
 ('56604', '136919121'),
 ('56604', '186856265'),
 ('56604', '487873315'),
 ('56604', '360233031'),
 ('56604', '131575184'),
 ('56604', '151564435'),
 ('56604', '20199180'),
 ('56604', '214801947'),
 ('56604', '302201808'),
 ('56604', '113545957'),
 ('56604', '222254722'),
 ('56604', '126992835'),
 ('56604', '142922629'),
 ('56604', '235746204'),
 ('56604', '328409902'),
 ('56604', '472316028'),
 ('56604', '526191441'),
 ('56604', '624455930'),
 ('56604', '179223309'),
 ('56604', '23720792'),
 ('56604', '78689377'),
 ('56604', '281317152'),
 ('56604', '588888571'),
 ('56604', '23887549'),
 ('56604', '188695511'),
 ('56604', '470207717'),
 ('56604', '31795984'),
 ('56604', '693150335'),
 ('56604', '559737811'),
 ('56604', '462468262'),
 ('56604', '205640328'),
 ('56604', '115774561'),
 ('56604', '3676059'),
 ('56604', '110881966'),
 ('56604', '460291471'),
 ('56604', '240617983'),
 ('56604', '162637605'),
 ('56604', '24278088'),
 ('56604', '6371'),
 ('56604', '220591346'),
 ('56604', '551610650'),
 ('56604', '1397481'),
 ('56604', '237318523'),
 ('56604', '586271927'),
 ('56604', '666094281'),
 ('56604', '138681828'),
 ('56604', '166767673'),
 ('56604', '435929076'),
 ('56604', '510331311'),
 ('56604', '480608763'),
 ('56604', '216132075'),
 ('56604', '31746367'),
 ('56604', '73886990'),
 ('56604', '222892558'),
 ('56604', '138446566'),
 ('56604', '281365134'),
 ('56604', '605694658'),
 ('56604', '29043680'),
 ('56604', '179146166'),
 ('56604', '249953241'),
 ('56604', '256218991'),
 ('56604', '589370912'),
 ('56604', '563827481'),
 ('56604', '171564576'),
 ('56604', '545855939'),
 ('56604', '461694427'),
 ('56604', '679800472'),
 ('56604', '332224693'),
 ('56604', '132930861'),
 ('56604', '120591149'),
 ('56604', '624254288'),
 ('56604', '155238333'),
 ('56604', '98241834'),
 ('56604', '278095494'),
 ('56604', '174530281'),
 ('56604', '7207693'),
 ('56604', '3461247'),
 ('56604', '161044634'),
 ('56604', '200574779'),
 ('56604', '401402807'),
 ('56604', '818357927'),
 ('56604', '104382647'),
 ('56604', '212458137'),
 ('56604', '167976202'),
 ('56604', '138628598')]

In [27]:
post_likes = pd.DataFrame(data_for_df, columns = ["post_id", "user_id"])

In [ ]:
data = json.load(open("user_likes.json", "r"))["users_likes"]
data_for_df = []
for i in data:
    data_for_df.extend(list(zip([i]*len(data[i]), map(str, data[i]))))
data_for_df

In [ ]:
post_likes = pd.DataFrame(data_for_df, columns = ["post_id", "user_id"])